seed: 1
work_dir: ./exp/asb/noun
run_mode: train

# feeder
feeder: feeders.feeder_asb.Feeder
train_feeder_args:
  data_path: data/asb/share_contex25_thresh0_noun/train_data_joint_200.npy
  label_path: data/asb/share_contex25_thresh0_noun/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  random_rot: True
  p_interval: [0.5, 1]
  window_size: 120
  normalization: False

test_feeder_args:
  data_path: data/asb/share_contex25_thresh0_noun/validation_data_joint_200.npy
  label_path: data/asb/share_contex25_thresh0_noun/validation_label.pkl
  debug: False
  window_size: 120
  p_interval: [0.95]

# model
model: model.ISTANet.Model
model_args:
  window_size: [20, 1, 2]
  num_frames: 120
  num_joints: 21
  num_persons: 2
  num_channels: 3
  num_classes: 90
  num_heads: 3
  kernel_size: [5, 5]
  use_pes: True
  config: [[64,  64,  16],
           [64,  64,  16], [64,  64,  16], 
           [64,  128, 32], [128, 128, 32],
           [128, 256, 64], [256, 256, 64], 
           [256, 256, 64], [256, 256, 64]]

#optim
optimizer: SGD
weight_decay: 0.0004
base_lr: 0.05
lr_decay_rate: 0.1
step: [25, 35, 50]
warm_up_epoch: 5
nesterov: True

# loss
loss: LabelSmoothingCrossEntropy
loss_args:
  smoothing: 0.1
  temperature: 1.1

# training
device: [0,1,2,3]
cuda_visible_device: '0,1,2,3'
batch_size: 52
test_batch_size: 52
num_epoch: 60
