seed: 1
work_dir: ./exp/sbu/noisy
run_mode: train

# feeder
feeder: feeders.feeder_sbu.Feeder
train_feeder_args:
  data_path: data/sbu/SBU-Kinect-Interaction-Skeleton/Noisy
  split: train
  fold: 0 # 0,1,2,3,4
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 60
  normalization: False
  random_rot: True
  p_interval: [0.5, 1]
  vel: False
  bone: False
  entity_rearrangement: True

test_feeder_args:
  data_path: data/sbu/SBU-Kinect-Interaction-Skeleton/Noisy
  split: test
  fold: 0 # 0,1,2,3,4
  debug: False
  window_size: 60
  normalization: False
  p_interval: [0.95]
  vel: False
  bone: False

# model
model: model.ISTANet.Model
model_args:
  window_size: [15, 15, 1]
  num_frames: 60
  num_joints: 15
  num_persons: 2
  num_channels: 3
  num_classes: 8
  num_heads: 3
  kernel_size: [5, 5]
  use_pes: True
  config: [[64,  64,  16], [64,  64,  16], 
           [64,  128, 32], [128, 128, 32],
           [128, 256, 64], [256, 256, 64]]
  att_drop: 0.1
  dropout: 0.1

#optim
optimizer: AdamW
optimizer_betas: [0.9, 0.999]
weight_decay: 0.0004
base_lr: 5.e-4
lr_decay_rate: 0.25
step: [35, 60, 90, 120]
warm_up_epoch: 5

# loss
loss: LabelSmoothingCrossEntropy
loss_args:
  smoothing: 0.15
  temperature: 1.0

# training
device: [0]
cuda_visible_device: '0'
batch_size: 32
test_batch_size: 32
num_epoch: 150